## MARKETING ANALYSIS

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("marketing_data.csv")

In [3]:
data.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Response,Complain,Country
0,1826,1970,Graduation,Divorced,84835.0,0,0,2014-06-16,0,189,...,6,1,0,0,0,0,0,1,0,Spain
1,1,1961,Graduation,Single,57091.0,0,0,2014-06-15,0,464,...,7,5,0,0,0,0,1,1,0,Canada
2,10476,1958,Graduation,Married,67267.0,0,1,2014-05-13,0,134,...,5,2,0,0,0,0,0,0,0,USA
3,1386,1967,Graduation,Together,32474.0,1,1,2014-05-11,0,10,...,2,7,0,0,0,0,0,0,0,Australia
4,5371,1989,Graduation,Single,21474.0,1,0,2014-04-08,0,6,...,2,7,1,0,0,0,0,1,0,Spain

In [4]:
data.shape

(2240, 28)

In [5]:
data.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', ' Income ',
       'Kidhome', 'Teenhome', 'Dt_Customer', 'Recency', 'MntWines',
       'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Response', 'Complain', 'Country'],
      dtype='object')

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4    Income              2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Response             2240 non-null   int64
 26  Complain             2240 non-null   int64
 27  Country              2240 non-null   object
dtypes: float64(1), int64(23), object(4)
memory usage: 490.1+ KB

In [7]:
data.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
 Income                24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Response                0
Complain                0
Country                 0
dtype: int64

In [8]:
missing_income_pct = data[' Income '].isnull().mean() * 100

missing_income_pct

np.float64(1.0714285714285714)

In [9]:
data.duplicated().sum()

np.int64(0)

In [10]:
data.value_counts('Education')

Education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64

In [11]:
data.value_counts("Marital_Status")

Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

In [12]:
data.value_counts("Country")

Country
Spain           1095
Saudi Arabia     337
Canada           268
Australia        160
India            148
Germany          120
USA              109
Mexico             3
Name: count, dtype: int64

In [13]:
data.describe()

,ID,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Response,Complain
count,2240.000000,2240.000000,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000
mean,5592.159821,1968.805804,52247.251354,0.444196,0.506250,49.109375,303.935714,26.302232,166.950000,37.525446,...,2.662054,5.790179,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.149107,0.009375
std,3246.662198,11.984069,25173.076661,0.538398,0.544538,28.962453,336.597393,39.773434,225.715373,54.628979,...,2.923101,3.250958,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.356274,0.096391
min,0.000000,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2828.250000,1959.000000,35303.000000,0.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,...,0.000000,3.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,5458.500000,1970.000000,51381.500000,0.000000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,...,2.000000,5.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,8427.750000,1977.000000,68522.000000,1.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,...,4.000000,8.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,11191.000000,1996.000000,666666.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,...,28.000000,13.000000,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [14]:
data["Year_Birth"].sort_values().head(20)

513     1893
827     1899
2233    1900
2171    1940
1740    1941
1208    1943
1644    1943
1209    1943
1202    1943
1475    1943
1693    1943
1350    1943
191     1944
502     1944
575     1944
2028    1944
227     1944
436     1944
1924    1944
524     1945
Name: Year_Birth, dtype: int64

In [15]:
data["Year_Birth"].describe()

count    2240.000000
mean     1968.805804
std        11.984069
min      1893.000000
25%      1959.000000
50%      1970.000000
75%      1977.000000
max      1996.000000
Name: Year_Birth, dtype: float64

In [16]:
data[" Income "].describe()

count      2216.000000
mean      52247.251354
std       25173.076661
min        1730.000000
25%       35303.000000
50%       51381.500000
75%       68522.000000
max      666666.000000
Name:  Income , dtype: float64

In [17]:
data[" Income "].sort_values(ascending=False).head(10)

527     666666.0
731     162397.0
497     160803.0
853     157733.0
2204    157243.0
325     157146.0
1925    156924.0
1826    153924.0
210     113734.0
832     105471.0
Name:  Income , dtype: float64

In [18]:
campaign_cols = [
    "AcceptedCmp1",
    "AcceptedCmp2",
    "AcceptedCmp3",
    "AcceptedCmp4",
    "AcceptedCmp5",
    "Response"
]

for col in campaign_cols:
    print("\n", col)
    print(data[col].value_counts())

 AcceptedCmp1
AcceptedCmp1
0    2096
1     144
Name: count, dtype: int64

 AcceptedCmp2
AcceptedCmp2
0    2210
1      30
Name: count, dtype: int64

 AcceptedCmp3
AcceptedCmp3
0    2077
1     163
Name: count, dtype: int64

 AcceptedCmp4
AcceptedCmp4
0    2073
1     167
Name: count, dtype: int64

 AcceptedCmp5
AcceptedCmp5
0    2077
1     163
Name: count, dtype: int64

 Response
Response
0    1906
1     334
Name: count, dtype: int64

In [19]:
channel_cols = [
    "NumWebPurchases",
    "NumCatalogPurchases",
    "NumStorePurchases",
    "NumWebVisitsMonth"
]

data[channel_cols].describe()

,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth
count,2240.000000,2240.000000,2240.000000,2240.000000
mean,4.084821,2.662054,5.790179,5.316518
std,2.778714,2.923101,3.250958,2.426645
min,0.000000,0.000000,0.000000,0.000000
25%,2.000000,0.000000,3.000000,3.000000
50%,4.000000,2.000000,5.000000,6.000000
75%,6.000000,4.000000,8.000000,7.000000
max,27.000000,28.000000,13.000000,20.000000

In [20]:
summary = pd.DataFrame({
    "Data_Type": data.dtypes,
    "Missing_Values": data.isnull().sum(),
    "Unique_Values": data.nunique()
})

summary

                    Data_Type  Missing_Values  Unique_Values
ID                      int64               0           2240
Year_Birth              int64               0             59
Education              object               0              5
Marital_Status         object               0              8
 Income               float64              24           1974
Kidhome                 int64               0              3
Teenhome                int64               0              3
Dt_Customer            object               0            663
Recency                 int64               0            100
MntWines                int64               0            776
MntFruits               int64               0            158
MntMeatProducts         int64               0            558
MntFishProducts         int64               0            182
MntSweetProducts        int64               0            177
MntGoldProds            int64               0            213
NumDealsPurchases       int64               0             15
NumWebPurchases         int64               0             15
NumCatalogPurchases     int64               0             14
NumStorePurchases       int64               0             14
NumWebVisitsMonth       int64               0             16
AcceptedCmp3            int64               0              2
AcceptedCmp4            int64               0              2
AcceptedCmp5            int64               0              2
AcceptedCmp1            int64               0              2
AcceptedCmp2            int64               0              2
Response                int64               0              2
Complain                int64               0              2
Country                object               0              8

In [21]:
data["Dt_Customer"] = pd.to_datetime(
    data["Dt_Customer"],
    errors="coerce"
)

In [22]:
data["Dt_Customer"].dtype

dtype('<M8[ns]')

In [23]:
data[data[" Income "].isna()][
    ["ID", "Year_Birth", "Education", "Marital_Status", "Country"]
]

         ID  Year_Birth   Education Marital_Status    Country
134    8996        1957         PhD        Married    Germany
262    1994        1983  Graduation        Married        USA
394    3769        1972         PhD       Together  Australia
449    5255        1986  Graduation         Single  Australia
525    8268        1961         PhD        Married     Canada
590   10629        1973    2n Cycle        Married    Germany
899   10475        1970      Master       Together        USA
997    9235        1957  Graduation         Single    Germany
1096   4345        1964    2n Cycle         Single  Australia
1185   7187        1969      Master       Together  Australia
1213   8720        1978    2n Cycle       Together      India
1312   8557        1982  Graduation         Single  Australia
1515   2863        1970  Graduation         Single      Spain
1558   2437        1989  Graduation        Married      Spain
1693   5250        1943      Master          Widow  Australia
1804   7281        1959         PhD         Single  Australia
1858   1612        1981         PhD         Single  Australia
1863   5079        1971  Graduation        Married  Australia
1880  10339        1954      Master       Together  Australia
1967   5798        1973      Master       Together    Germany
1983   2902        1958  Graduation       Together  Australia
2139   3117        1955  Graduation         Single  Australia
2165   7244        1951  Graduation         Single  Australia
2170   1295        1963  Graduation        Married     Canada

In [24]:
income_median = data[" Income "].median()

data["Income"] = data[" Income "].fillna(income_median)

In [25]:
data=data.drop([" Income "],axis=1)

In [26]:
data["Income"].isna().sum()

np.int64(0)

In [74]:
data['Income'].shape

(2240,)

In [27]:
#Missing Income values were imputed using the median because income is a skewed
#numerical variable and only 1.07% of records were missing.

In [29]:
data[data["Year_Birth"] < 1920][
    ["ID", "Year_Birth", "Income", "Education", "Marital_Status"]
]

         ID  Year_Birth   Income Education Marital_Status
513   11004        1893  60182.0  2n Cycle         Single
827    1150        1899  83532.0       PhD       Together
2233   7829        1900  36640.0  2n Cycle       Divorced

In [30]:
year_datacollected = 2014

In [31]:
data["Age"] = year_datacollected - data["Year_Birth"]

In [32]:
data["Age"].describe()

count    2240.000000
mean       45.194196
std        11.984069
min        18.000000
25%        37.000000
50%        44.000000
75%        55.000000
max       121.000000
Name: Age, dtype: float64

In [33]:
data[data["Age"] > 100][
    ["ID", "Year_Birth", "Age"]
]

         ID  Year_Birth  Age
513   11004        1893  121
827    1150        1899  115
2233   7829        1900  114

In [34]:
data.loc[data["Age"] > 100, "Age"] = np.nan

In [35]:
data["Age"].isna().sum()

np.int64(3)

In [36]:
#CAtegorical columns

In [37]:
data.value_counts('Education')

Education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64

In [38]:
data["Marital_Status"].value_counts()

Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
YOLO          2
Absurd        2
Name: count, dtype: int64

In [39]:
data[data["Marital_Status"].isin(["Absurd", "YOLO"])]

,ID,Year_Birth,Education,Marital_Status,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,...,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Response,Complain,Country,Income,Age
103,492,1973,PhD,YOLO,0,1,2012-10-18,3,322,3,...,0,0,0,0,0,0,0,Canada,48432.0,41.0
104,11133,1973,PhD,YOLO,0,1,2012-10-18,3,322,3,...,0,0,0,0,0,1,0,India,48432.0,41.0
1068,4369,1957,Master,Absurd,0,0,2014-01-10,48,240,67,...,0,0,0,0,0,0,0,Canada,65487.0,57.0
1339,7734,1993,Graduation,Absurd,0,0,2012-12-19,58,471,102,...,0,0,1,1,0,1,0,Australia,79244.0,21.0

In [40]:
data["Marital_Status"] = data["Marital_Status"].replace(
    {
        "Absurd": "Other",
        "YOLO": "Other"
    }
)

In [41]:
data["Marital_Status"].value_counts()

Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Other         4
Alone         3
Name: count, dtype: int64

In [42]:
data["Country"].value_counts()

Country
Spain           1095
Saudi Arabia     337
Canada           268
Australia        160
India            148
Germany          120
USA              109
Mexico             3
Name: count, dtype: int64

In [43]:
# Check numerical variables for negative values

In [44]:
numeric_cols = data.select_dtypes(include=np.number).columns

(data[numeric_cols] < 0).sum().sort_values(ascending=False)

ID                     0
NumCatalogPurchases    0
Income                 0
Complain               0
Response               0
AcceptedCmp2           0
AcceptedCmp1           0
AcceptedCmp5           0
AcceptedCmp4           0
AcceptedCmp3           0
NumWebVisitsMonth      0
NumStorePurchases      0
NumWebPurchases        0
Year_Birth             0
NumDealsPurchases      0
MntGoldProds           0
MntSweetProducts       0
MntFishProducts        0
MntMeatProducts        0
MntFruits              0
MntWines               0
Recency                0
Teenhome               0
Kidhome                0
Age                    0
dtype: int64

In [45]:
#Check income outliers

In [46]:
data["Income"].describe()

count      2240.000000
mean      52237.975446
std       25037.955891
min        1730.000000
25%       35538.750000
50%       51381.500000
75%       68289.750000
max      666666.000000
Name: Income, dtype: float64

In [47]:
data["Income"].sort_values(ascending=False).head(10)

527     666666.0
731     162397.0
497     160803.0
853     157733.0
2204    157243.0
325     157146.0
1925    156924.0
1826    153924.0
210     113734.0
832     105471.0
Name: Income, dtype: float64

In [48]:
#Check purchase variables

In [49]:
purchase_cols = [
    "MntWines",
    "MntFruits",
    "MntMeatProducts",
    "MntFishProducts",
    "MntSweetProducts",
    "MntGoldProds",
    "NumDealsPurchases",
    "NumWebPurchases",
    "NumCatalogPurchases",
    "NumStorePurchases"
]

(data[purchase_cols] < 0).sum()

MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
dtype: int64

In [50]:
#Check campaign variables

In [51]:
campaign_cols = [
    "AcceptedCmp1",
    "AcceptedCmp2",
    "AcceptedCmp3",
    "AcceptedCmp4",
    "AcceptedCmp5",
    "Response"
]

for col in campaign_cols:
    print(col, data[col].unique())

AcceptedCmp1 [0 1]
AcceptedCmp2 [0 1]
AcceptedCmp3 [0 1]
AcceptedCmp4 [0 1]
AcceptedCmp5 [0 1]
Response [1 0]

## feature engineering.

In [52]:
#total spending

In [53]:
spending_cols = [
    "MntWines",
    "MntFruits",
    "MntMeatProducts",
    "MntFishProducts",
    "MntSweetProducts",
    "MntGoldProds"
]

data["Total_Spending"] = data[spending_cols].sum(axis=1)

In [54]:
#total purchases:

In [55]:
purchase_cols = [
    "NumWebPurchases",
    "NumCatalogPurchases",
    "NumStorePurchases"
]

data["Total_Purchases"] = data[purchase_cols].sum(axis=1)

In [56]:
#total campaign responses:

In [57]:
campaign_cols = [
    "AcceptedCmp1",
    "AcceptedCmp2",
    "AcceptedCmp3",
    "AcceptedCmp4",
    "AcceptedCmp5"
]

data["Total_Campaign_Responses"] = data[campaign_cols].sum(axis=1)

In [58]:
#Create a customer segment

In [59]:
data["Customer_Segment"] = pd.qcut(
    data["Total_Spending"],
    q=3,
    labels=["Low Value", "Medium Value", "High Value"]
)

In [60]:
data["Customer_Segment"].value_counts()

Customer_Segment
Low Value       748
High Value      747
Medium Value    745
Name: count, dtype: int64

## Final quality check

In [61]:
print("Rows:", data.shape[0])
print("Columns:", data.shape[1])
print("Duplicate rows:", data.duplicated().sum())
print("Missing values:")
print(data.isnull().sum()[data.isnull().sum() > 0])

Rows: 2240
Columns: 33
Duplicate rows: 0
Missing values:
Age    3
dtype: int64

In [62]:
# Saving the cleaned dataset

In [69]:
df=data.to_csv(
    "marketing_data_cleaned.csv",
    index=False
)

In [71]:
df=pd.read_csv("marketing_data_cleaned.csv")

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        2240 non-null   int64
 1   Year_Birth                2240 non-null   int64
 2   Education                 2240 non-null   object
 3   Marital_Status            2240 non-null   object
 4   Kidhome                   2240 non-null   int64
 5   Teenhome                  2240 non-null   int64
 6   Dt_Customer               2240 non-null   object
 7   Recency                   2240 non-null   int64
 8   MntWines                  2240 non-null   int64
 9   MntFruits                 2240 non-null   int64
 10  MntMeatProducts           2240 non-null   int64
 11  MntFishProducts           2240 non-null   int64
 12  MntSweetProducts          2240 non-null   int64
 13  MntGoldProds              2240 non-null   int64
 14  NumDealsPurchases         2240 non-null   int64
 15  NumWebPurchases           2240 non-null   int64
 16  NumCatalogPurchases       2240 non-null   int64
 17  NumStorePurchases         2240 non-null   int64
 18  NumWebVisitsMonth         2240 non-null   int64
 19  AcceptedCmp3              2240 non-null   int64
 20  AcceptedCmp4              2240 non-null   int64
 21  AcceptedCmp5              2240 non-null   int64
 22  AcceptedCmp1              2240 non-null   int64
 23  AcceptedCmp2              2240 non-null   int64
 24  Response                  2240 non-null   int64
 25  Complain                  2240 non-null   int64
 26  Country                   2240 non-null   object
 27  Income                    2240 non-null   float64
 28  Age                       2237 non-null   float64
 29  Total_Spending            2240 non-null   int64
 30  Total_Purchases           2240 non-null   int64
 31  Total_Campaign_Responses  2240 non-null   int64
 32  Customer_Segment          2240 non-null   object
dtypes: float64(2), int64(26), object(5)
memory usage: 577.6+ KB